export default {
  BG_COLOR: { dark: "#0A0A0A;", light: "#dce0dd" },
  MAIN_RED: "#EC1D24",
  MAIN_WHITE: "#FFFFFF",
  MAIN_BLACK: "#000000",
  MAIN_GRAY: "#929292",
  MAIN_LIGHT_GRAY: "#ebebeb",
  MAIN_DARK_GRAY: "#6e6e6e",
  MAIN_YELLOW: "#f7d35e",
  MAIN_BLUE: "#00baff",
  MAIN_PURPLE: "#8d1b7f",
  MAIN_GREEN: "#00b300",
  MAIN_ORANGE: "#ffa500",
  MAIN_PINK: "#ff00ff",
  MAIN_RED_LIGHT: "#ffcdd2",
  MAIN_BLUE_LIGHT: "#b3e5fc",
  MAIN_PURPLE_LIGHT: "#ede7f6",
  MAIN_GREEN_LIGHT: "#c8e6c9",
  MAIN_ORANGE_LIGHT: "#ffecb3",
  MAIN_PINK_LIGHT: "#ffe0f1",
  MAIN_BLACK_LIGHT: "#212121",
  MAIN_GRAY_LIGHT: "#bdbdbd",
  MAIN_GRAY_DARK: "#757575",
  MAIN_GRAY_DARKER: "#424242",
  MAIN_GRAY_DARKEST: "#212121",
  MAIN_GRAY_LIGHTEST: "#e0e0e0",
  MAIN_WHITE_LIGHT: "#ffffff",
  MAIN_WHITE_DARK: "#fafafa",
  MAIN_WHITE_DARKER: "#f5f5f5",
  MAIN_WHITE_DARKEST: "#eeeeee",
  MAIN_WHITE_LIGHTEST: "#ffffff",
  MAIN_RED_LIGHT: "#ffcdd2",
  MAIN_BLUE_LIGHT: "#b3e5fc",
};
